# Generated by Django 5.0.6 on 2024-06-04 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_note_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
