# Generated by Django 5.0.6 on 2024-06-10 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_note_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='user',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='user',
            new_name='creator',
        ),
    ]
