# Generated by Django 5.0.6 on 2024-06-10 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_user_category_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='creator',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='note',
            old_name='creator',
            new_name='user',
        ),
    ]
